IF (OBJECT_ID('dbo.CHAT_GPT_API_KEYS') IS NOT NULL) AND (OBJECTPROPERTY(OBJECT_ID('dbo.CHAT_GPT_API_KEYS'), 'IsUserTable')=1)
	DROP TABLE dbo.CHAT_GPT_API_KEYS
GO

CREATE TABLE dbo.CHAT_GPT_API_KEYS
(
	API_KEY			NVARCHAR(70)	NOT NULL
)
GO

-- Primary Key
ALTER TABLE dbo.CHAT_GPT_API_KEYS WITH NOCHECK ADD
	CONSTRAINT PK_CHAT_GPT_API_KEYS PRIMARY KEY CLUSTERED (API_KEY) ON [PRIMARY]
GO

INSERT	dbo.CHAT_GPT_API_KEYS
(
	API_KEY
)
VALUES
(
	'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'
);