USE STB
GO

CREATE OR ALTER PROCEDURE SP_ALBUM_ADD_ALBUM_ACCESS
	@ALBUM_NAME			NVARCHAR(200)
	,@ROLE_ID			INT
WITH ENCRYPTION
AS
SET NOCOUNT ON;

IF NOT EXISTS (SELECT 1 FROM dbo.ALBUM_ACCESS WHERE ALBUM_NAME = @ALBUM_NAME AND ROLE_ID = @ROLE_ID)
    BEGIN
	INSERT	dbo.ALBUM_ACCESS (ALBUM_NAME, ROLE_ID)
	VALUES	(@ALBUM_NAME, @ROLE_ID);

	SELECT	CAST(1 AS BIT) AS SUCCESS;
    END
ELSE
    BEGIN
	SELECT	CAST(0 AS BIT) AS SUCCESS;
    END

SET NOCOUNT OFF;
GO