USE STB
GO

CREATE OR ALTER PROCEDURE SP_ALBUM_UPSERT_PHOTO
	@ALBUM_NAME			NVARCHAR(200)
	,@FILE_NAME			NVARCHAR(500)
	,@WIDTH				INT
	,@HEIGHT			INT
	,@FILE_SIZE			BIGINT
	,@DISPLAY_ORDER			INT = 0
WITH ENCRYPTION
AS
SET NOCOUNT ON;

IF EXISTS (SELECT 1 FROM dbo.ALBUM_PHOTOS WHERE ALBUM_NAME = @ALBUM_NAME AND FILE_NAME = @FILE_NAME AND IS_DELETED = 0)
    BEGIN
	UPDATE	dbo.ALBUM_PHOTOS
	SET	[WIDTH] = @WIDTH
		,[HEIGHT] = @HEIGHT
		,FILE_SIZE = @FILE_SIZE
		,DISPLAY_ORDER = @DISPLAY_ORDER
		,MODIFIED_DATE = GETDATE()
	WHERE	ALBUM_NAME = @ALBUM_NAME
	AND	FILE_NAME = @FILE_NAME
	AND	IS_DELETED = 0;
    END
ELSE
    BEGIN
	INSERT INTO dbo.ALBUM_PHOTOS (ALBUM_NAME, FILE_NAME, [WIDTH], [HEIGHT], FILE_SIZE, DISPLAY_ORDER)
	VALUES (@ALBUM_NAME, @FILE_NAME, @WIDTH, @HEIGHT, @FILE_SIZE, @DISPLAY_ORDER);
    END

SELECT SCOPE_IDENTITY() AS PHOTO_ID;

SET NOCOUNT OFF;
GO
