USE STB
GO

CREATE OR ALTER PROCEDURE SP_ALBUM_USER_LOGIN
	@PHONE_NUMBER			NVARCHAR(20)
	,@PASSWORD_HASH			NVARCHAR(128)
WITH ENCRYPTION
AS
SET NOCOUNT ON;

DECLARE	@IS_VALID			BIT = 0;
DECLARE	@USER_NAME			NVARCHAR(50) = NULL;

SELECT	@IS_VALID = 1
	,@USER_NAME = [USER_NAME]
FROM	dbo.ALBUM_USERS
WHERE	PHONE_NUMBER = @PHONE_NUMBER
AND	PASSWORD_HASH = @PASSWORD_HASH
AND	IS_ACTIVE = 1;

IF (@IS_VALID = 1)
    BEGIN
	UPDATE	dbo.ALBUM_USERS
	SET	LAST_LOGIN_DATE = GETDATE()
	WHERE	PHONE_NUMBER = @PHONE_NUMBER;
    END

SELECT	@IS_VALID AS IS_VALID
	,ISNULL(@USER_NAME, '') AS [USER_NAME];

SET NOCOUNT OFF;
GO