USE STB
GO

CREATE OR ALTER PROCEDURE SP_ALBUM_REMOVE_USER_ROLE
	@USER_ROLE_ID			INT
WITH ENCRYPTION
AS
SET NOCOUNT ON;

DELETE	dbo.ALBUM_USER_ROLES
WHERE	USER_ROLE_ID = @USER_ROLE_ID;

SELECT	CAST(@@ROWCOUNT AS BIT) AS SUCCESS;

SET NOCOUNT OFF;
GO