USE STB
GO

CREATE OR ALTER PROCEDURE SP_ALBUM_GET_ALL_ALBUM_ACCESS
WITH ENCRYPTION
AS
SET NOCOUNT ON;

SELECT	A.ACCESS_ID
	,A.ALBUM_NAME
	,A.ROLE_ID
	,R.ROLE_NAME
FROM	dbo.ALBUM_ACCESS A
JOIN	dbo.ALBUM_ROLES R ON A.ROLE_ID = R.ROLE_ID
ORDER BY A.ALBUM_NAME, R.ROLE_NAME;

SET NOCOUNT OFF;
GO