USE STB
GO

CREATE OR ALTER PROCEDURE SP_ALBUM_GET_ALL_USER_ROLES
WITH ENCRYPTION
AS
SET NOCOUNT ON;

SELECT	UR.USER_ROLE_ID
	,UR.PHONE_NUMBER
	,U.[USER_NAME]
	,UR.ROLE_ID
	,R.ROLE_NAME
FROM	dbo.ALBUM_USER_ROLES AS UR
	INNER JOIN dbo.ALBUM_ROLES AS R ON UR.ROLE_ID = R.ROLE_ID
	INNER JOIN dbo.ALBUM_USERS AS U ON UR.PHONE_NUMBER = U.PHONE_NUMBER
ORDER BY U.PHONE_NUMBER, R.ROLE_NAME;

SET NOCOUNT OFF;
GO