USE STB
GO

CREATE OR ALTER PROCEDURE [dbo].[SP_ALBUM_CREATE_ALBUM]
	@ALBUM_NAME		NVARCHAR(200)
	,@DISPLAY_NAME		NVARCHAR(200)
WITH ENCRYPTION
AS
SET NOCOUNT ON;

IF EXISTS (SELECT 1 FROM dbo.ALBUMS WHERE ALBUM_NAME = @ALBUM_NAME AND IS_DELETED = 0)
    BEGIN
	SELECT	CAST(0 AS BIT) AS [SUCCESS]
	RETURN;
    END

	-- 이전에 삭제된 동일 이름이 있으면 복원
IF EXISTS (SELECT 1 FROM dbo.ALBUMS WHERE ALBUM_NAME = @ALBUM_NAME AND IS_DELETED = 1)
    BEGIN
	UPDATE	dbo.ALBUMS
	SET	DISPLAY_NAME = @DISPLAY_NAME
		,IS_DELETED = 0
		,MODIFIED_DATE = GETDATE()
	WHERE	ALBUM_NAME = @ALBUM_NAME

	SELECT	CAST(1 AS BIT) AS SUCCESS
	RETURN;
    END

INSERT	dbo.ALBUMS (ALBUM_NAME, DISPLAY_NAME)
VALUES (@ALBUM_NAME, @DISPLAY_NAME)

SELECT	CAST(1 AS BIT) AS SUCCESS

SET NOCOUNT OFF;
GO
