USE STB
GO

CREATE OR ALTER PROCEDURE SP_ALBUM_REMOVE_ALBUM_ACCESS
	@ACCESS_ID			INT
WITH ENCRYPTION
AS
SET NOCOUNT ON;

DELETE	dbo.ALBUM_ACCESS
WHERE	ACCESS_ID = @ACCESS_ID;

SELECT	CAST(@@ROWCOUNT AS BIT) AS SUCCESS;

SET NOCOUNT OFF;
GO