USE STB
GO

CREATE OR ALTER PROCEDURE SP_ALBUM_GET_USER_ROLES
	@PHONE_NUMBER			NVARCHAR(20)
WITH ENCRYPTION
AS
SET NOCOUNT ON;

SELECT	R.ROLE_ID
	,R.ROLE_NAME
FROM	dbo.ALBUM_USER_ROLES UR
JOIN	dbo.ALBUM_ROLES R ON UR.ROLE_ID = R.ROLE_ID
WHERE	UR.PHONE_NUMBER = @PHONE_NUMBER;

SET NOCOUNT OFF;
GO