USE STB
GO

CREATE OR ALTER PROCEDURE [dbo].[SP_ALBUM_DELETE_ALBUM]
	@ALBUM_NAME		NVARCHAR(200)
WITH ENCRYPTION
AS
SET NOCOUNT ON;

IF NOT EXISTS (SELECT 1 FROM dbo.ALBUMS WHERE ALBUM_NAME = @ALBUM_NAME AND IS_DELETED = 0)
    BEGIN
	SELECT	CAST(0 AS BIT) AS [SUCCESS]
	RETURN;
    END

UPDATE	dbo.ALBUMS
SET	IS_DELETED = 1
	,MODIFIED_DATE = GETDATE()
WHERE	ALBUM_NAME = @ALBUM_NAME;

SELECT	CAST(1 AS BIT) AS SUCCESS;

SET NOCOUNT OFF;
GO