USE STB
GO

CREATE OR ALTER PROCEDURE SP_ALBUM_GET_PHOTOS
	@ALBUM_NAME			NVARCHAR(200)
WITH ENCRYPTION
AS
SET NOCOUNT ON;

SELECT	PHOTO_ID
	,ALBUM_NAME
	,FILE_NAME
	,[WIDTH]
	,[HEIGHT]
	,FILE_SIZE
	,DISPLAY_ORDER
FROM	dbo.ALBUM_PHOTOS
WHERE	ALBUM_NAME = @ALBUM_NAME
AND	IS_DELETED = 0
ORDER BY DISPLAY_ORDER, FILE_NAME;

SET NOCOUNT OFF;
GO
