USE STB
GO

CREATE OR ALTER PROCEDURE SP_ALBUM_ADD_ROLE
	@ROLE_NAME			NVARCHAR(100)
WITH ENCRYPTION
AS
SET NOCOUNT ON;

IF NOT EXISTS (SELECT 1 FROM dbo.ALBUM_ROLES WHERE ROLE_NAME = @ROLE_NAME)
    BEGIN
	INSERT INTO dbo.ALBUM_ROLES (ROLE_NAME)
	VALUES (@ROLE_NAME);

	SELECT CAST(1 AS BIT) AS SUCCESS, SCOPE_IDENTITY() AS ROLE_ID;
    END
ELSE
    BEGIN
	SELECT CAST(0 AS BIT) AS SUCCESS, CAST(0 AS INT) AS ROLE_ID;
    END

SET NOCOUNT OFF;
GO