USE STB
GO

CREATE OR ALTER PROCEDURE SP_ALBUM_DELETE_ROLE
	@ROLE_ID			INT
WITH ENCRYPTION
AS
SET NOCOUNT ON;

-- 시스템 마스터 역할은 삭제 불가
IF EXISTS (SELECT 1 FROM dbo.ALBUM_ROLES WHERE ROLE_ID = @ROLE_ID AND ROLE_NAME = N'시스템 마스터')
    BEGIN
	SELECT	CAST(0 AS BIT) AS SUCCESS;
	RETURN;
    END

-- 연관된 사용자 역할 삭제
DELETE	dbo.ALBUM_USER_ROLES
WHERE	ROLE_ID = @ROLE_ID;

-- 연관된 앨범 접근 삭제
DELETE	dbo.ALBUM_ACCESS
WHERE	ROLE_ID = @ROLE_ID;

-- 역할 삭제
DELETE	dbo.ALBUM_ROLES
WHERE	ROLE_ID = @ROLE_ID;

SELECT	CAST(1 AS BIT) AS SUCCESS;

SET NOCOUNT OFF;
GO