USE STB
GO

CREATE OR ALTER PROCEDURE SP_ALBUM_ASSIGN_USER_ROLE
	@PHONE_NUMBER			NVARCHAR(20)
	,@ROLE_ID			INT
WITH ENCRYPTION
AS
SET NOCOUNT ON;

IF NOT EXISTS (SELECT 1 FROM dbo.ALBUM_USER_ROLES WHERE PHONE_NUMBER = @PHONE_NUMBER AND ROLE_ID = @ROLE_ID)
    BEGIN
	INSERT	dbo.ALBUM_USER_ROLES (PHONE_NUMBER, ROLE_ID)
	VALUES	(@PHONE_NUMBER, @ROLE_ID);

	SELECT	CAST(1 AS BIT) AS SUCCESS;
    END
ELSE
    BEGIN
	SELECT	CAST(0 AS BIT) AS SUCCESS;
    END

SET NOCOUNT OFF;
GO