IF OBJECT_ID('SP_GET_FORTUNE_MESSAGE') IS NOT NULL
	DROP PROCEDURE SP_GET_FORTUNE_MESSAGE
GO

CREATE PROCEDURE SP_GET_FORTUNE_MESSAGE
WITH ENCRYPTION
AS
SET NOCOUNT ON;

SELECT	TOP 1 [Message]
	,FORTUNE_NO
FROM	dbo.FORTUNE_MESSAGES
ORDER BY newid();

SET NOCOUNT OFF;
GO

EXEC	dbo.SP_GET_FORTUNE_MESSAGE