IF OBJECT_ID('SP_INSERT_ERROR_LOG') IS NOT NULL
	DROP PROCEDURE SP_INSERT_ERROR_LOG
GO

CREATE PROCEDURE SP_INSERT_ERROR_LOG
	@ERROR_CODE			INT
	,@MESSAGE			NVARCHAR(MAX)
	,@STACK_TRACE			NVARCHAR(MAX)
	,@REQUEST_METHOD		NVARCHAR(10)
	,@REQUEST_PATH			NVARCHAR(500)
	,@REQUEST_BODY			NVARCHAR(MAX)
	,@USER_IP			NVARCHAR(50)
WITH ENCRYPTION
AS
SET NOCOUNT ON;

INSERT	dbo.ERROR_LOGS
(
	ERROR_CODE
	,[MESSAGE]
	,STACK_TRACE
	,REQUEST_METHOD
	,REQUEST_PATH
	,REQUEST_BODY
	,USER_IP
	,CREATED_DATE
)
VALUES
(
	@ERROR_CODE
	,@MESSAGE
	,@STACK_TRACE
	,@REQUEST_METHOD
	,@REQUEST_PATH
	,@REQUEST_BODY
	,@USER_IP
	,GETDATE()
);

SET NOCOUNT OFF;
GO
