USE StockAutoTrader
GO

CREATE OR ALTER PROCEDURE SP_STOCK_UPDATE_STOCK
	@STOCK_CODE		NVARCHAR(20)
	,@STOCK_NAME		NVARCHAR(100)
	,@MARKET_TYPE		NVARCHAR(20)
	,@IS_ACTIVE		BIT
	,@IS_WATCH_LIST		BIT
WITH ENCRYPTION
AS
SET NOCOUNT ON;

IF NOT EXISTS (SELECT 1 FROM dbo.STOCKS WHERE STOCK_CODE = @STOCK_CODE)
    BEGIN
	SELECT	CAST(0 AS BIT) AS [SUCCESS];
	RETURN;
    END

UPDATE	dbo.STOCKS
SET	STOCK_NAME = @STOCK_NAME
	,MARKET_TYPE = @MARKET_TYPE
	,IS_ACTIVE = @IS_ACTIVE
	,IS_WATCH_LIST = @IS_WATCH_LIST
	,UPDATED_AT = GETDATE()
WHERE	STOCK_CODE = @STOCK_CODE;

SELECT	CAST(1 AS BIT) AS [SUCCESS];

SET NOCOUNT OFF;
GO
