USE StockAutoTrader
GO

CREATE OR ALTER PROCEDURE SP_STOCK_USER_LOGIN
	@LOGIN_ID		NVARCHAR(50)
	,@PASSWORD_HASH		NVARCHAR(256)
WITH ENCRYPTION
AS
SET NOCOUNT ON;

DECLARE	@IS_VALID		BIT = 0;
DECLARE	@USER_NAME		NVARCHAR(100) = NULL;

SELECT	@IS_VALID = 1
	,@USER_NAME = [USER_NAME]
FROM	dbo.STOCK_USERS
WHERE	LOGIN_ID = @LOGIN_ID
AND	PASSWORD_HASH = @PASSWORD_HASH
AND	IS_ACTIVE = 1;

IF (@IS_VALID = 1)
    BEGIN
	UPDATE	dbo.STOCK_USERS
	SET	LAST_LOGIN_DATE = GETDATE()
	WHERE	LOGIN_ID = @LOGIN_ID;
    END

SELECT	@IS_VALID AS IS_VALID
	,ISNULL(@USER_NAME, '') AS [USER_NAME];

SET NOCOUNT OFF;
GO
