USE StockAutoTrader
GO

CREATE OR ALTER PROCEDURE SP_STOCK_DELETE_STOCK
	@STOCK_CODE		NVARCHAR(20)
WITH ENCRYPTION
AS
SET NOCOUNT ON;

IF NOT EXISTS (SELECT 1 FROM dbo.STOCKS WHERE STOCK_CODE = @STOCK_CODE)
    BEGIN
	SELECT	CAST(0 AS BIT) AS [SUCCESS];
	RETURN;
    END

UPDATE	dbo.STOCKS
SET	IS_ACTIVE = 0
	,UPDATED_AT = GETDATE()
WHERE	STOCK_CODE = @STOCK_CODE;

SELECT	CAST(1 AS BIT) AS [SUCCESS];

SET NOCOUNT OFF;
GO
