USE StockAutoTrader
GO

CREATE OR ALTER PROCEDURE SP_STOCK_CREATE_STOCK
	@STOCK_CODE		NVARCHAR(20)
	,@STOCK_NAME		NVARCHAR(100)
	,@MARKET_TYPE		NVARCHAR(20)
WITH ENCRYPTION
AS
SET NOCOUNT ON;

IF EXISTS (SELECT 1 FROM dbo.STOCKS WHERE STOCK_CODE = @STOCK_CODE)
    BEGIN
	SELECT	CAST(0 AS BIT) AS [SUCCESS];
	RETURN;
    END

INSERT INTO dbo.STOCKS 
(
	STOCK_CODE
	,STOCK_NAME
	,MARKET_TYPE
)
VALUES (@STOCK_CODE, @STOCK_NAME, @MARKET_TYPE);

SELECT	CAST(1 AS BIT) AS [SUCCESS];

SET NOCOUNT OFF;
GO
