USE StockAutoTrader
GO

CREATE OR ALTER PROCEDURE SP_STOCK_GET_ORDERS
WITH ENCRYPTION
AS
SET NOCOUNT ON;

SELECT	ID
	,ORDER_NO
	,PARENT_ORDER_ID
	,STOCK_CODE
	,STOCK_NAME
	,ORDER_TYPE
	,ORDER_PRICE
	,ORDER_QUANTITY
	,FILLED_QUANTITY
	,FILLED_PRICE
	,COST_BASIS_PRICE
	,ESTIMATED_COMMISSION
	,ESTIMATED_TAX
	,REALIZED_PROFIT
	,NET_REALIZED_PROFIT
	,ORDER_STATUS
	,REASON
	,CREATED_AT
	,UPDATED_AT
	,FILLED_AT
	,LAST_RECONCILED_AT
	,RECONCILIATION_NOTE
FROM	dbo.ORDERS
ORDER BY CREATED_AT DESC;

SET NOCOUNT OFF;
GO
