-- ============================================
-- StockAutoTrader Database Schema
-- SQL Server용 주식 자동매매 DB 스키마
-- ============================================

USE master;
GO

IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = 'StockAutoTrader')
    BEGIN
	CREATE DATABASE StockAutoTrader;
    END
GO

USE StockAutoTrader;
GO

-- 주식 종목 정보
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'STOCKS')
    BEGIN
	CREATE TABLE STOCKS
	(
		STOCK_CODE		NVARCHAR(20)	PRIMARY KEY
		,STOCK_NAME		NVARCHAR(100)	NOT NULL
		,MARKET_TYPE		NVARCHAR(20)	NOT NULL DEFAULT 'KOSPI'	-- KOSPI, KOSDAQ
		,IS_ACTIVE		BIT		NOT NULL DEFAULT 1
		,IS_WATCH_LIST		BIT		NOT NULL DEFAULT 0		-- 감시 종목 여부
		,CREATED_AT		DATETIME2	NOT NULL DEFAULT GETDATE()
		,UPDATED_AT		DATETIME2	NOT NULL DEFAULT GETDATE()
	);
    END
GO

-- 기존 테이블에 IS_WATCH_LIST 컬럼이 없으면 추가
IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('STOCKS') AND name = 'IS_WATCH_LIST')
    BEGIN
	ALTER TABLE STOCKS ADD IS_WATCH_LIST BIT NOT NULL DEFAULT 0;
    END
GO

-- 보유 종목 (포트폴리오)
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'HOLDINGS')
    BEGIN
	CREATE TABLE HOLDINGS
	(
		ID			INT		IDENTITY(1,1) PRIMARY KEY
		,STOCK_CODE		NVARCHAR(20)	NOT NULL
		,STOCK_NAME		NVARCHAR(100)	NOT NULL
		,QUANTITY		INT		NOT NULL
		,AVG_BUY_PRICE		DECIMAL(18,2)	NOT NULL
		,CURRENT_PRICE		DECIMAL(18,2)	NULL
		,PROFIT_LOSS_RATE	DECIMAL(10,4)	NULL
		,HIGHEST_PRICE		DECIMAL(18,2)	NULL
		,BOUGHT_AT		DATETIME2	NOT NULL DEFAULT GETDATE()
		,UPDATED_AT		DATETIME2	NOT NULL DEFAULT GETDATE()
		,CONSTRAINT FK_HOLDINGS_STOCKS FOREIGN KEY (STOCK_CODE) REFERENCES STOCKS(STOCK_CODE)
    );
END
GO

-- 주문 내역
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'ORDERS')
    BEGIN
	CREATE TABLE ORDERS
	(
		ID			INT		IDENTITY(1,1) PRIMARY KEY
		,PARENT_ORDER_ID	INT		NULL
		,ORDER_NO		NVARCHAR(50)	NULL				-- KIS API 주문번호
		,STOCK_CODE		NVARCHAR(20)	NOT NULL
		,STOCK_NAME		NVARCHAR(100)	NOT NULL
		,ORDER_TYPE		NVARCHAR(10)	NOT NULL			-- BUY, SELL
		,ORDER_PRICE		DECIMAL(18,2)	NOT NULL
		,ORDER_QUANTITY		INT		NOT NULL
		,FILLED_QUANTITY	INT		NOT NULL DEFAULT 0
		,FILLED_PRICE		DECIMAL(18,2)	NULL
		,COST_BASIS_PRICE	DECIMAL(18,2)	NULL
		,ESTIMATED_COMMISSION DECIMAL(18,2) NOT NULL DEFAULT 0
		,ESTIMATED_TAX		DECIMAL(18,2)	NOT NULL DEFAULT 0
		,REALIZED_PROFIT	DECIMAL(18,2)	NULL
		,NET_REALIZED_PROFIT DECIMAL(18,2)	NULL
		,ORDER_STATUS		NVARCHAR(20)	NOT NULL DEFAULT 'PENDING'	-- PENDING, ACCEPTED, FILLED, PARTIAL, CANCELLED, FAILED
		,REASON			NVARCHAR(500)	NULL				-- 매매 사유
		,CREATED_AT		DATETIME2	NOT NULL DEFAULT GETDATE()
		,UPDATED_AT		DATETIME2	NOT NULL DEFAULT GETDATE()
		,FILLED_AT		DATETIME2	NULL
		,LAST_RECONCILED_AT	DATETIME2	NULL
		,RECONCILIATION_NOTE NVARCHAR(500)	NULL
	);
END
GO

-- 기존 주문 테이블에 체결 대사/손익 컬럼 추가
IF COL_LENGTH('dbo.ORDERS', 'PARENT_ORDER_ID') IS NULL ALTER TABLE dbo.ORDERS ADD PARENT_ORDER_ID INT NULL;
IF COL_LENGTH('dbo.ORDERS', 'COST_BASIS_PRICE') IS NULL ALTER TABLE dbo.ORDERS ADD COST_BASIS_PRICE DECIMAL(18,2) NULL;
IF COL_LENGTH('dbo.ORDERS', 'ESTIMATED_COMMISSION') IS NULL ALTER TABLE dbo.ORDERS ADD ESTIMATED_COMMISSION DECIMAL(18,2) NOT NULL DEFAULT 0;
IF COL_LENGTH('dbo.ORDERS', 'ESTIMATED_TAX') IS NULL ALTER TABLE dbo.ORDERS ADD ESTIMATED_TAX DECIMAL(18,2) NOT NULL DEFAULT 0;
IF COL_LENGTH('dbo.ORDERS', 'REALIZED_PROFIT') IS NULL ALTER TABLE dbo.ORDERS ADD REALIZED_PROFIT DECIMAL(18,2) NULL;
IF COL_LENGTH('dbo.ORDERS', 'NET_REALIZED_PROFIT') IS NULL ALTER TABLE dbo.ORDERS ADD NET_REALIZED_PROFIT DECIMAL(18,2) NULL;
IF COL_LENGTH('dbo.ORDERS', 'FILLED_AT') IS NULL ALTER TABLE dbo.ORDERS ADD FILLED_AT DATETIME2 NULL;
IF COL_LENGTH('dbo.ORDERS', 'LAST_RECONCILED_AT') IS NULL ALTER TABLE dbo.ORDERS ADD LAST_RECONCILED_AT DATETIME2 NULL;
IF COL_LENGTH('dbo.ORDERS', 'RECONCILIATION_NOTE') IS NULL ALTER TABLE dbo.ORDERS ADD RECONCILIATION_NOTE NVARCHAR(500) NULL;
GO

-- 시세 데이터 (일봉)
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'DAILY_PRICES')
    BEGIN
	CREATE TABLE DAILY_PRICES
	(
		ID			INT		IDENTITY(1,1) PRIMARY KEY
		,STOCK_CODE		NVARCHAR(20)	NOT NULL
		,TRADE_DATE		DATE		NOT NULL
		,OPEN_PRICE		DECIMAL(18,2)	NOT NULL
		,HIGH_PRICE		DECIMAL(18,2)	NOT NULL
		,LOW_PRICE		DECIMAL(18,2)	NOT NULL
		,CLOSE_PRICE		DECIMAL(18,2)	NOT NULL
		,VOLUME			BIGINT		NOT NULL
		,CREATED_AT		DATETIME2	NOT NULL DEFAULT GETDATE()
		,CONSTRAINT UQ_DAILY_PRICES UNIQUE (STOCK_CODE, TRADE_DATE)
	);
    END
GO

-- 거래 로그
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'TRADE_LOGS')
    BEGIN
	CREATE TABLE TRADE_LOGS
	(
		ID			INT		IDENTITY(1,1) PRIMARY KEY
		,LOG_LEVEL		NVARCHAR(20)	NOT NULL
		,[MESSAGE]		NVARCHAR(MAX)	NOT NULL
		,STOCK_CODE		NVARCHAR(20)	NULL
		,ORDER_ID		INT		NULL
		,CREATED_AT		DATETIME2	NOT NULL DEFAULT GETDATE()
	);
    END
GO

-- 일일 수익 요약
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'DAILY_PROFIT_SUMMARY')
    BEGIN
	CREATE TABLE DAILY_PROFIT_SUMMARY
	(
		ID			INT		IDENTITY(1,1) PRIMARY KEY
		,TRADE_DATE		DATE		NOT NULL UNIQUE
		,TOTAL_BUY_AMOUNT	DECIMAL(18,2)	NOT NULL DEFAULT 0
		,TOTAL_SELL_AMOUNT	DECIMAL(18,2)	NOT NULL DEFAULT 0
		,REALIZED_PROFIT	DECIMAL(18,2)	NOT NULL DEFAULT 0
		,TRADING_COST		DECIMAL(18,2)	NOT NULL DEFAULT 0
		,NET_REALIZED_PROFIT DECIMAL(18,2)	NOT NULL DEFAULT 0
		,UNREALIZED_PROFIT	DECIMAL(18,2)	NOT NULL DEFAULT 0
		,TOTAL_HOLDING_VALUE	DECIMAL(18,2)	NOT NULL DEFAULT 0
		,CREATED_AT		DATETIME2	NOT NULL DEFAULT GETDATE()
	);
    END
GO

-- 인덱스 생성
IF COL_LENGTH('dbo.HOLDINGS', 'HIGHEST_PRICE') IS NULL ALTER TABLE dbo.HOLDINGS ADD HIGHEST_PRICE DECIMAL(18,2) NULL;
IF COL_LENGTH('dbo.DAILY_PROFIT_SUMMARY', 'TRADING_COST') IS NULL ALTER TABLE dbo.DAILY_PROFIT_SUMMARY ADD TRADING_COST DECIMAL(18,2) NOT NULL DEFAULT 0;
IF COL_LENGTH('dbo.DAILY_PROFIT_SUMMARY', 'NET_REALIZED_PROFIT') IS NULL ALTER TABLE dbo.DAILY_PROFIT_SUMMARY ADD NET_REALIZED_PROFIT DECIMAL(18,2) NOT NULL DEFAULT 0;

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('dbo.ORDERS') AND name = 'IX_ORDERS_ACTIVE_LOOKUP')
	CREATE INDEX IX_ORDERS_ACTIVE_LOOKUP ON dbo.ORDERS(STOCK_CODE, ORDER_TYPE, ORDER_STATUS)
	INCLUDE (ORDER_NO, CREATED_AT);

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID('dbo.HOLDINGS') AND name = 'UX_HOLDINGS_ACTIVE_STOCK_CODE')
	CREATE UNIQUE INDEX UX_HOLDINGS_ACTIVE_STOCK_CODE ON dbo.HOLDINGS(STOCK_CODE) WHERE QUANTITY > 0;

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_ORDERS_STOCK_CODE')
	CREATE INDEX IX_ORDERS_STOCK_CODE ON ORDERS(STOCK_CODE);

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_ORDERS_CREATED_AT')
	CREATE INDEX IX_ORDERS_CREATED_AT ON ORDERS(CREATED_AT DESC);

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_DAILY_PRICES_STOCK_CODE_DATE')
	CREATE INDEX IX_DAILY_PRICES_STOCK_CODE_DATE ON DAILY_PRICES(STOCK_CODE, TRADE_DATE DESC);

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_HOLDINGS_STOCK_CODE')
	CREATE INDEX IX_HOLDINGS_STOCK_CODE ON HOLDINGS(STOCK_CODE);

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_TRADE_LOGS_CREATED_AT')
	CREATE INDEX IX_TRADE_LOGS_CREATED_AT ON TRADE_LOGS(CREATED_AT DESC);
GO

-- API 접근 토큰
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'ACCESS_TOKENS')
    BEGIN
	CREATE TABLE ACCESS_TOKENS
	(
		ID			INT		IDENTITY(1,1) PRIMARY KEY
		,TOKEN_TYPE		NVARCHAR(50)	NOT NULL DEFAULT 'KIS'		-- 토큰 유형
		,ACCESS_TOKEN		NVARCHAR(MAX)	NOT NULL
		,EXPIRES_AT		DATETIME2	NOT NULL
		,CREATED_AT		DATETIME2	NOT NULL DEFAULT GETDATE()
	);
    END
GO

-- 사용자 관리
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'STOCK_USERS')
    BEGIN
	CREATE TABLE STOCK_USERS
	(
		USER_ID			INT		IDENTITY(1,1) PRIMARY KEY
		,LOGIN_ID		NVARCHAR(50)	NOT NULL UNIQUE
		,PASSWORD_HASH		NVARCHAR(256)	NOT NULL
		,USER_NAME		NVARCHAR(100)	NOT NULL
		,IS_ACTIVE		BIT		NOT NULL DEFAULT 1
		,LAST_LOGIN_DATE	DATETIME2	NULL
		,CREATED_AT		DATETIME2	NOT NULL DEFAULT GETDATE()
	);
    END
GO

-- 관리자 계정 시드
IF NOT EXISTS (SELECT 1 FROM dbo.STOCK_USERS WHERE LOGIN_ID = '01064374825')
    BEGIN
	INSERT INTO dbo.STOCK_USERS (LOGIN_ID, PASSWORD_HASH, USER_NAME)
	VALUES ('01064374825', '416E586910BD9DDAE55910336B30DE2D9994D4C8D97DCEBFFFC01D40D39DB59D67E90E745707E862CA80F8E6B6EA43B305BC9D7F5BD1D845BFAEB09D75DE6D1E', 'Admin');
    END
GO

PRINT 'StockAutoTrader database schema created successfully.';
GO
