IF OBJECT_ID('SP_GET_CHAT_GPT_API_KEY') IS NOT NULL
	DROP PROCEDURE SP_GET_CHAT_GPT_API_KEY
GO

CREATE PROCEDURE SP_GET_CHAT_GPT_API_KEY
WITH ENCRYPTION
AS
SET NOCOUNT ON;

SELECT	*
FROM	dbo.CHAT_GPT_API_KEYS;

SET NOCOUNT OFF;
GO

EXEC	dbo.SP_GET_CHAT_GPT_API_KEY