IF (OBJECT_ID('dbo.ACCOUNTS') IS NOT NULL) AND (OBJECTPROPERTY(OBJECT_ID('dbo.ACCOUNTS'), 'IsUserTable')=1)
	DROP TABLE dbo.ACCOUNTS
GO

CREATE TABLE dbo.ACCOUNTS
(
	ACCOUNT_NO		NVARCHAR(50)	NOT NULL
	,BALANCE		INT		NOT NULL
)
GO

-- Primary Key
ALTER TABLE dbo.ACCOUNTS WITH NOCHECK ADD
	CONSTRAINT PK_ACCOUNTS PRIMARY KEY CLUSTERED (ACCOUNT_NO) ON [PRIMARY]
GO

INSERT	dbo.ACCOUNTS
(
	ACCOUNT_NO
	,BALANCE
)
VALUES
(
	'110-263-905697'
	,0
);