USE STB
GO

IF (OBJECT_ID('dbo.ALBUMS') IS NOT NULL) AND (OBJECTPROPERTY(OBJECT_ID('dbo.ALBUMS'), 'IsUserTable')=1)
	DROP TABLE dbo.ALBUMS
GO

CREATE TABLE dbo.ALBUMS
(
	ALBUM_ID		INT		IDENTITY(1,1) NOT NULL
	,ALBUM_NAME		NVARCHAR(200)	NOT NULL
	,DISPLAY_NAME		NVARCHAR(200)	NOT NULL
	,IS_DELETED		BIT		NOT NULL DEFAULT(0)
	,CREATED_DATE		DATETIME	NOT NULL DEFAULT(GETDATE())
	,MODIFIED_DATE		DATETIME	NOT NULL DEFAULT(GETDATE())
)
GO

-- Primary Key
ALTER TABLE dbo.ALBUMS WITH NOCHECK ADD
	CONSTRAINT PK_ALBUMS PRIMARY KEY CLUSTERED (ALBUM_ID) ON [PRIMARY]
GO

-- Unique Key
ALTER TABLE dbo.ALBUMS WITH NOCHECK ADD
	CONSTRAINT UQ_ALBUMS_ALBUM_NAME UNIQUE (ALBUM_NAME)
GO

-- 초기 앨범 등록
INSERT INTO ALBUMS (ALBUM_NAME, DISPLAY_NAME) VALUES ('yoogeon_50th', '유건이 50일')