USE STB
GO

IF (OBJECT_ID('dbo.ALBUM_ACCESS') IS NOT NULL) AND (OBJECTPROPERTY(OBJECT_ID('dbo.ALBUM_ACCESS'), 'IsUserTable')=1)
	DROP TABLE dbo.ALBUM_ACCESS
GO

CREATE TABLE ALBUM_ACCESS
(
	ACCESS_ID		INT		IDENTITY(1,1)	NOT NULL
	,ALBUM_NAME		NVARCHAR(200)	NOT NULL
	,ROLE_ID		INT		NOT NULL
	,CREATED_DATE		DATETIME	NOT NULL DEFAULT GETDATE()
);

ALTER TABLE dbo.ALBUM_ACCESS WITH NOCHECK ADD
	CONSTRAINT PK_ALBUM_ACCESS PRIMARY KEY CLUSTERED (ACCESS_ID) ON [PRIMARY]
GO

CREATE UNIQUE NONCLUSTERED INDEX UX_ALBUM_ACCESS ON dbo.ALBUM_ACCESS (ALBUM_NAME, ROLE_ID) ON [PRIMARY]
GO

-- yoogeon_50th 앨범은 '유건이 부모' 역할만 접근 가능
INSERT INTO ALBUM_ACCESS (ALBUM_NAME, ROLE_ID)
SELECT 'yoogeon_50th', ROLE_ID FROM ALBUM_ROLES WHERE ROLE_NAME = N'유건이 부모';
