USE STB
GO

IF (OBJECT_ID('dbo.ALBUM_ROLES') IS NOT NULL) AND (OBJECTPROPERTY(OBJECT_ID('dbo.ALBUM_ROLES'), 'IsUserTable')=1)
	DROP TABLE dbo.ALBUM_ROLES
GO

CREATE TABLE ALBUM_ROLES
(
	ROLE_ID			INT		IDENTITY(1,1)	NOT NULL
	,ROLE_NAME		NVARCHAR(100)	NOT NULL
	,CREATED_DATE		DATETIME	NOT NULL DEFAULT GETDATE()
);

ALTER TABLE dbo.ALBUM_ROLES WITH NOCHECK ADD
	CONSTRAINT PK_ALBUM_ROLES PRIMARY KEY CLUSTERED (ROLE_ID) ON [PRIMARY]
GO

CREATE UNIQUE NONCLUSTERED INDEX UX_ALBUM_ROLES_NAME ON dbo.ALBUM_ROLES (ROLE_NAME) ON [PRIMARY]
GO

-- 초기 역할 등록
INSERT INTO ALBUM_ROLES (ROLE_NAME) VALUES (N'시스템 마스터');
INSERT INTO ALBUM_ROLES (ROLE_NAME) VALUES (N'유건이 부모');
