USE STB
GO

IF (OBJECT_ID('dbo.ALBUM_USER_ROLES') IS NOT NULL) AND (OBJECTPROPERTY(OBJECT_ID('dbo.ALBUM_USER_ROLES'), 'IsUserTable')=1)
	DROP TABLE dbo.ALBUM_USER_ROLES
GO

CREATE TABLE ALBUM_USER_ROLES
(
	USER_ROLE_ID		INT		IDENTITY(1,1)	NOT NULL
	,PHONE_NUMBER		NVARCHAR(20)	NOT NULL
	,ROLE_ID		INT		NOT NULL
	,CREATED_DATE		DATETIME	NOT NULL DEFAULT GETDATE()
);

ALTER TABLE dbo.ALBUM_USER_ROLES WITH NOCHECK ADD
	CONSTRAINT PK_ALBUM_USER_ROLES PRIMARY KEY CLUSTERED (USER_ROLE_ID) ON [PRIMARY]
GO

CREATE UNIQUE NONCLUSTERED INDEX UX_ALBUM_USER_ROLES ON dbo.ALBUM_USER_ROLES (PHONE_NUMBER, ROLE_ID) ON [PRIMARY]
GO

-- 01064374825에 시스템 마스터 역할 부여
INSERT INTO ALBUM_USER_ROLES (PHONE_NUMBER, ROLE_ID)
SELECT '01064374825', ROLE_ID FROM ALBUM_ROLES WHERE ROLE_NAME = N'시스템 마스터';
