USE STB
GO

IF (OBJECT_ID('dbo.ALBUM_PHOTOS') IS NOT NULL) AND (OBJECTPROPERTY(OBJECT_ID('dbo.ALBUM_PHOTOS'), 'IsUserTable')=1)
	DROP TABLE dbo.ALBUM_PHOTOS
GO

CREATE TABLE ALBUM_PHOTOS
(
	PHOTO_ID		INT IDENTITY(1,1)	NOT NULL
	,ALBUM_NAME		NVARCHAR(200)		NOT NULL
	,[FILE_NAME]		NVARCHAR(500)		NOT NULL
	,[WIDTH]		INT			NOT NULL DEFAULT 0
	,[HEIGHT]		INT			NOT NULL DEFAULT 0
	,FILE_SIZE		BIGINT			NOT NULL DEFAULT 0
	,DISPLAY_ORDER		INT			NOT NULL DEFAULT 0
	,IS_DELETED		BIT			NOT NULL DEFAULT 0
	,CREATED_DATE		DATETIME		NOT NULL DEFAULT GETDATE()
	,MODIFIED_DATE		DATETIME		NULL
);

-- Primary Key
ALTER TABLE dbo.ALBUM_PHOTOS WITH NOCHECK ADD
	CONSTRAINT PK_ALBUM_PHOTOS PRIMARY KEY CLUSTERED (PHOTO_ID) ON [PRIMARY]
GO

-- Unique Index (active photos only)
CREATE UNIQUE NONCLUSTERED INDEX UX_ALBUM_PHOTOS_ACTIVE ON dbo.ALBUM_PHOTOS (ALBUM_NAME, [FILE_NAME]) WHERE IS_DELETED = 0
GO
