IF (OBJECT_ID('dbo.CHAT_GPT_USING_LOGS') IS NOT NULL) AND (OBJECTPROPERTY(OBJECT_ID('dbo.CHAT_GPT_USING_LOGS'), 'IsUserTable')=1)
	DROP TABLE dbo.CHAT_GPT_USING_LOGS
GO

CREATE TABLE dbo.CHAT_GPT_USING_LOGS
(
	CHAT_GPT_USING_LOG_ID		INT		IDENTITY(1,1) NOT NULL
	,USING_TYPE			NVARCHAR(50)	NOT NULL
	,[MESSAGE]			NVARCHAR(MAX)	NOT NULL
	,RESPONSE			NVARCHAR(MAX)	NOT NULL
	,INSERT_DATE			DATETIME	NOT NULL
)
GO

-- Primary Key
ALTER TABLE dbo.CHAT_GPT_USING_LOGS WITH NOCHECK ADD
	CONSTRAINT PK_CHAT_GPT_USING_LOGS PRIMARY KEY CLUSTERED (CHAT_GPT_USING_LOG_ID) ON [PRIMARY]
GO