IF (OBJECT_ID('dbo.ERROR_LOGS') IS NOT NULL) AND (OBJECTPROPERTY(OBJECT_ID('dbo.ERROR_LOGS'), 'IsUserTable')=1)
	DROP TABLE dbo.ERROR_LOGS
GO

CREATE TABLE dbo.ERROR_LOGS
(
	ERROR_LOG_ID			INT		IDENTITY(1,1) NOT NULL
	,ERROR_CODE			INT		NULL
	,[MESSAGE]			NVARCHAR(MAX)	NOT NULL
	,STACK_TRACE			NVARCHAR(MAX)	NULL
	,REQUEST_METHOD			NVARCHAR(10)	NOT NULL
	,REQUEST_PATH			NVARCHAR(500)	NOT NULL
	,REQUEST_BODY			NVARCHAR(MAX)	NULL
	,USER_IP			NVARCHAR(50)	NULL
	,CREATED_DATE			DATETIME	NOT NULL DEFAULT(GETDATE())
)
GO

-- Primary Key
ALTER TABLE dbo.ERROR_LOGS WITH NOCHECK ADD
	CONSTRAINT PK_ERROR_LOGS PRIMARY KEY CLUSTERED (ERROR_LOG_ID) ON [PRIMARY]
GO

-- Index
CREATE NONCLUSTERED INDEX IX_ERROR_LOGS_CREATED_DATE ON dbo.ERROR_LOGS (CREATED_DATE DESC)
GO
